[project]
site_name = "FRCDesign.org"
site_description = "A community driven learning course, and resource hub for FRC Design and CAD, using Onshape"
site_author = "FRCDesign Team"
site_url = "https://zensical.frcdesign.org/"
repo_url = "https://github.com/frcdesign/FRCDesign-Zensical"
repo_name = "FRCDesign.org"
extra_css = ["stylesheets/extra.css", "stylesheets/slides.css"]
extra_javascript = ["javascripts/slides.js"]
docs_dir = "docs"
nav = [
    {"Home" = "index.md"},
    {"Website Feature Guide" = "website-feature-guide/index.md"}
]

[project.theme]
variant = "modern"
favicon = "/assets/images/icon.svg"
language = "en"

features = [
    "content.action.edit",
    "content.code.annotate",
    "header.autohide",
    "navigation.footer",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "navigation.tabs",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "green"
accent = "green"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
primary = "green"
accent = "green"

[project.theme.icon]
#logo = "./docs/assets/images/main-logo.svg"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/frcdesign/FRCDesign-Zensical"


